import { describe, expect, it } from 'vitest';
import { balanceSources, bradleyTerry, preferenceOutcome, skillToRating, skillToScore, wilsonInterval, type Comparison } from '../worker/ranking';
const make = (a:string,b:string,outcome:number,n:number,source:'human'|'ai'='human'):Comparison[] => Array.from({length:n},(_,i) => ({a,b,outcome,weight:1,ballot:`${source}-${a}-${b}-${i}`,source}));
describe('pairwise ranking',() => {
  it('maps the five-level scale symmetrically',() => { expect([-2,-1,0,1,2].map(preferenceOutcome)).toEqual([0,.25,.5,.75,1]); });
  it('converts skill to a centered score and Elo-style rating',() => { expect(skillToScore(0)).toBe(50); expect(skillToRating(0)).toBe(1500); expect(skillToRating(Math.LN10)).toBeCloseTo(1900); expect(skillToScore(1)+skillToScore(-1)).toBeCloseTo(100); });
  it('ranks a consistent winner above its opponent, with finite estimates',() => { const r=bradleyTerry.fit(['a','b'],make('a','b',1,40)); expect(r[0].id).toBe('a'); expect(r[0].score).toBeGreaterThan(80); expect(r.every(x => Number.isFinite(x.rating))).toBe(true); });
  it('respects preference strength',() => { const strong=bradleyTerry.fit(['a','b'],make('a','b',1,20))[0]; const mild=bradleyTerry.fit(['a','b',],make('a','b',.75,20))[0]; expect(strong.score).toBeGreaterThan(mild.score); });
  it('gives ties equal strengths and half wins',() => { const r=bradleyTerry.fit(['a','b'],make('a','b',.5,30)); expect(r[0].score).toBeCloseTo(50); expect(r[1].rating).toBeCloseTo(1500); expect(r[0].win_rate).toBe(.5); });
  it('is invariant to swapping pair orientation',() => { const a=bradleyTerry.fit(['a','b'],make('a','b',.75,15)); const b=bradleyTerry.fit(['a','b'],make('b','a',.25,15)); expect(a[0].score).toBeCloseTo(b[0].score); });
  it('propagates strength through the comparison graph',() => { const r=bradleyTerry.fit(['a','b','c'],[...make('a','b',.8,30),...make('b','c',.8,30)]); expect(r.map(s=>s.id)).toEqual(['a','b','c']); });
  it('narrows confidence intervals with more consistent data',() => { const a=bradleyTerry.fit(['a','b'],make('a','b',.6,4))[0], b=bradleyTerry.fit(['a','b'],make('a','b',.6,100))[0]; expect(b.ci[1]-b.ci[0]).toBeLessThan(a.ci[1]-a.ci[0]); expect(a.low_confidence).toBe(true); });
  it('marks disconnected systems and absent observations low confidence',() => { const r=bradleyTerry.fit(['a','b','c'],make('a','b',.6,50)); expect(r.every(s=>s.low_confidence)).toBe(true); expect(r.find(s=>s.id==='c')?.comparisons).toBe(0); });
  it('does not report false certainty for a single unjudged system',()=> { const r=bradleyTerry.fit(['only'],[])[0]; expect(r.ci[1]-r.ci[0]).toBeGreaterThan(90); expect(r.low_confidence).toBe(true); });
  it('does not multiply comparison counts by the number of metric observations',() => { const base=make('a','b',.75,1)[0]; const r=bradleyTerry.fit(['a','b'],Array.from({length:6},()=>({...base,weight:1/6}))); expect(r[0].comparisons).toBe(1); });
  it('uses source shares instead of source vote counts',() => { const c=balanceSources([...make('a','b',1,10),...make('a','b',0,1000,'ai')],.5,.5); const mass=(s:string)=>c.filter(x=>x.source===s).reduce((n,x)=>n+x.weight,0); expect(mass('human')).toBeCloseTo(mass('ai')); expect(bradleyTerry.fit(['a','b'],c)[0].score).toBeCloseTo(50); });
  it('obeys configured shares and handles absent or zero-weight sources',() => { const c=balanceSources([...make('a','b',1,10),...make('a','b',0,10,'ai')],.8,.2); expect(bradleyTerry.fit(['a','b'],c)[0].id).toBe('a'); expect(balanceSources(make('a','b',1,2),0,1)).toEqual([]); expect(balanceSources(make('a','b',1,2),.5,.5)[0].weight).toBe(1); });
  it('returns bounded, nondegenerate Wilson intervals, including extremes',() => { expect(wilsonInterval(0,0)).toEqual([0,1]); const [lo,hi]=wilsonInterval(10,10); expect(lo).toBeGreaterThan(0); expect(lo).toBeLessThan(1); expect(hi).toBeCloseTo(1); expect(wilsonInterval(50,100)[1]-wilsonInterval(50,100)[0]).toBeLessThan(wilsonInterval(5,10)[1]-wilsonInterval(5,10)[0]); });
});
