import { useState, type FormEvent } from 'react';
import { LockSimpleIcon } from '@phosphor-icons/react/dist/csr/LockSimple';
import { UploadSimpleIcon } from '@phosphor-icons/react/dist/csr/UploadSimple';
import { CheckIcon } from '@phosphor-icons/react/dist/csr/Check';
import { PlusIcon } from '@phosphor-icons/react/dist/csr/Plus';
import { api } from '../api';
import { PageHeader, ErrorState, Select } from '../components';
import { METRICS, METRIC_LABELS, TASK_LABELS, applicableMetrics, type SystemInfo } from '../../shared/domain';

interface Catalog { systems: SystemInfo[]; topics: {id:string;motion:string;category:string;active:number;metadata_json:string}[]; responses: {id:string;task:string;display_version:number}[]; standards: {id:string;title:string}[]; judges: {id:string;display_name:string}[]; weights: {task:string;metric:string;weight:number}[]; source: {human:number;ai:number}; }
type Field = { name:string; label:string; multiline?:boolean; optional?:boolean; options?:[string,string][]; value?:string; type?:string };
const entityOptions: [string,string][] = [['systems','System / configuration'],['topics','Topic / motion'],['responses','Response / run / Opposition pipeline'],['standardized_rebuttal_tasks','Standardized rebuttal task'],['ai_judges','AI judge'],['ai_votes','AI judgment']];

export default function Admin() {
  const [secret,setSecret] = useState(''), [catalog,setCatalog] = useState<Catalog | null>(null), [error,setError] = useState(''), [success,setSuccess] = useState(''), [busy,setBusy] = useState(false);
  const [tab,setTab] = useState('manual'), [entity,setEntity] = useState('systems'), [task,setTask] = useState('government');
  const [json,setJson] = useState('{\n  "systems": [],\n  "topics": [],\n  "responses": []\n}');
  const [editId,setEditId] = useState(''), [display,setDisplay] = useState(''), [raw,setRaw] = useState('');
  async function load() { const next = await api<Catalog>('/admin/catalog', {}, secret); setCatalog(next); }
  async function perform(action:()=>Promise<unknown>, message:string) { setBusy(true); setError(''); setSuccess(''); try { await action(); setSuccess(message); await load(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function unlock(e:FormEvent) { e.preventDefault(); await perform(load,'Admin session unlocked.'); }
  const references = (key:'systems'|'topics'|'responses'|'standards'|'judges'): [string,string][] => (catalog?.[key] || []).map(r => [r.id,`${r.id}${'display_name' in r ? ` · ${r.display_name}` : ''}`]);
  const basic = (name:string,label:string,extra:Partial<Field> = {}):Field => ({name,label,...extra});
  let fields:Field[] = [];
  if (entity === 'systems') fields = [basic('id','Unique system ID'),basic('display_name','Display name'),basic('provider','Provider'),basic('model','Underlying model'),basic('interface','Product / interface'),basic('reasoning','Reasoning setting',{optional:true}),basic('configuration','Tools / configuration notes',{multiline:true,optional:true})];
  if (entity === 'topics') fields = [basic('id','Unique topic ID'),basic('motion','Motion',{multiline:true}),basic('category','Category',{options:[['Serious','Serious'],['Informal','Informal']]}),basic('metadata_json','Future metadata (JSON object)',{value:'{}',optional:true})];
  if (entity === 'responses') fields = [basic('id','Unique response ID'),basic('system_id','System / pipeline configuration',{options:references('systems')}),basic('topic_id','Topic',{options:references('topics')}),basic('prompt','Exact prompt',{multiline:true}),basic('raw_output','Raw output (immutable)',{multiline:true}),basic('display_output',task === 'full_opposition' ? 'Constructive material (prediction + rebuttal are assembled automatically)' : 'Sanitized display output',{multiline:true}),basic('generated_at','Generation timestamp (ISO UTC)',{value:new Date().toISOString()}),basic('interface','Generation interface'),basic('reasoning','Reasoning setting',{optional:true}),basic('configuration','Tools / configuration',{multiline:true,optional:true}),basic('context_id','Context / thread ID'),basic('sample','Run / sample number',{type:'number',value:'1'}),basic('duration_ms','Duration (milliseconds)',{type:'number',optional:true}),...(task === 'standardized_rebuttal' ? [basic('standardized_task_id','Shared Government case',{options:references('standards')})] : []),...(['rebuttal','full_opposition'].includes(task) ? [basic('prediction_response_id','Prediction response ID',{options:references('responses').filter(([id]) => catalog?.responses.find(r => r.id === id)?.task === 'prediction')})] : []),...(task === 'full_opposition' ? [basic('rebuttal_response_id','Fresh-context rebuttal response ID',{options:references('responses').filter(([id]) => catalog?.responses.find(r => r.id === id)?.task === 'rebuttal')})] : [])];
  if (entity === 'standardized_rebuttal_tasks') fields = [basic('id','Unique task ID'),basic('title','Case title'),basic('topic_id','Topic',{options:references('topics')}),basic('government_response_id','Optional Government response ID',{optional:true,options:[['','None'],...references('responses').filter(([id]) => catalog?.responses.find(r => r.id === id)?.task === 'government')]}),basic('case_text','Common sanitized Government case',{multiline:true})];
  if (entity === 'ai_judges') fields = [basic('id','Unique judge ID'),basic('system_id','Judge system',{options:references('systems')}),basic('display_name','Judge display name'),basic('version','Judge version')];
  if (entity === 'ai_votes') fields = [basic('id','Unique judgment ID'),basic('judge_id','AI judge',{options:references('judges')}),basic('response_a','Response A ID',{options:references('responses')}),basic('response_b','Response B ID',{options:references('responses')}),basic('overall','Overall preference',{options:[['2','A much better'],['1','A better'],['0','Tie'],['-1','B better'],['-2','B much better']]}),basic('snapshot_a','Exact response A text seen by offline judge',{multiline:true}),basic('snapshot_b','Exact response B text seen by offline judge',{multiline:true}),basic('version','Judgment version'),basic('judged_at','Judged timestamp (ISO UTC)',{value:new Date().toISOString()}),basic('explanation','Optional explanation',{multiline:true,optional:true}),...METRICS.map(m => basic(`metric_${m}`,METRIC_LABELS[m],{optional:true,options:[['','Skip'],['2','A much better'],['1','A better'],['0','Tie'],['-1','B better'],['-2','B much better']]}))];
  async function create(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget;
    const data: Record<string,unknown> = Object.fromEntries(new FormData(form));
    for (const [k,v] of Object.entries(data)) if (v === '') { if (['reasoning','duration_ms','government_response_id','explanation'].includes(k)) data[k] = null; else delete data[k]; }
    const payload: Record<string,unknown> = {};
    if (entity === 'responses') {
      data.task = task; data.sample = Number(data.sample); if (data.duration_ms != null) data.duration_ms = Number(data.duration_ms);
      if (task === 'prediction') payload.opposition_predictions = [{response_id:data.id}];
      if (task === 'rebuttal') payload.opposition_rebuttals = [{response_id:data.id,prediction_response_id:data.prediction_response_id,fresh_context:1}];
      if (task === 'full_opposition') payload.opposition_preps = [{response_id:data.id,prediction_response_id:data.prediction_response_id,rebuttal_response_id:data.rebuttal_response_id}];
      delete data.prediction_response_id; delete data.rebuttal_response_id;
    }
    if (entity === 'ai_votes') {
      data.overall = Number(data.overall); const metrics: Record<string,number> = {};
      for (const m of METRICS) { if (data[`metric_${m}`] != null) metrics[m] = Number(data[`metric_${m}`]); delete data[`metric_${m}`]; } data.metrics = metrics;
    }
    payload[entity] = [data];
    await perform(() => api('/admin/import',{method:'POST',body:JSON.stringify(payload)},secret),'Record imported and relationships validated.');
  }
  async function loadDisplay(id:string) {
    setEditId(id); setDisplay(''); setRaw(''); if (!id) return;
    await perform(async () => { const run = await api<{display_output:string;raw_output:string}>(`/admin/responses/${id}`,{},secret); setDisplay(run.display_output); setRaw(run.raw_output); },'Response loaded.');
  }
  async function saveWeights(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = new FormData(e.currentTarget); if (!catalog) return;
    await perform(() => api('/admin/weights',{method:'PUT',body:JSON.stringify({source:{human:Number(form.get('human'))/100,ai:Number(form.get('ai'))/100},benchmark:catalog.weights.map(w => ({...w,weight:Number(form.get(`${w.task}:${w.metric}`))/100}))})},secret),'Ranking weights saved.');
  }
  return <div className="page admin-page"><PageHeader title="Admin" description="Import offline results, edit display text, and configure ranking weights." action={catalog && <button className="button small" onClick={() => {setCatalog(null);setSecret('');setRaw('');setDisplay('');setSuccess('');}}>Lock admin</button>} />{!catalog ? <form className="admin-lock" onSubmit={unlock}><LockSimpleIcon size={30} /><h2>Administrator access</h2><p className="muted">Use the backend admin secret. User PINs do not grant access.</p><label>Admin secret<input type="password" value={secret} onChange={e => setSecret(e.target.value)} autoComplete="off" required minLength={32} /></label><button className="button dark" disabled={busy}>Unlock admin</button><p className="caption">Kept in memory for this page only.</p>{error && <ErrorState message={error} />}</form> : <><div className="admin-tabs" role="group" aria-label="Admin tools">{[['manual','Manual entry'],['import','JSON import'],['display','Display editor'],['catalog','Catalog'],['weights','Ranking weights']].map(([v,label]) => <button className={tab === v ? 'active' : ''} key={v} onClick={() => {setTab(v);setError('');setSuccess('');}}>{label}</button>)}</div>{error && <ErrorState message={error} />}{success && <div className="notice" role="status"><CheckIcon />{success}</div>}
    {tab === 'manual' && <section><div className="filter-row admin-entity"><Select label="Record type" value={entity} onChange={setEntity} options={entityOptions} />{entity === 'responses' && <Select label="Task / stage" value={task} onChange={setTask} options={[...Object.entries(TASK_LABELS),['rebuttal','Opposition rebuttal (pipeline stage)']]} />}</div>{entity === 'responses' && <p className="notice">Import prediction first, then its rebuttal in a fresh context, then the full preparation. Cross-system stages are supported; select a system entry that names the complete pipeline.</p>}<form className="admin-form" key={`${entity}:${task}`} onSubmit={create}>{fields.map(field => <label className={field.multiline ? 'wide' : ''} key={field.name}>{field.label}{field.optional && <span className="muted"> · optional</span>}{field.options ? <select name={field.name} required={!field.optional}>{field.options.map(([v,label]) => <option key={v} value={v}>{label}</option>)}</select> : field.multiline ? <textarea name={field.name} rows={6} required={!field.optional} /> : <input name={field.name} type={field.type || 'text'} defaultValue={field.value} required={!field.optional} min={field.name === 'sample' ? 1 : 0} />}</label>)}<div className="wide"><button className="button dark" disabled={busy}><PlusIcon />{busy ? 'Importing…' : 'Validate & create'}</button></div></form></section>}
    {tab === 'import' && <section className="import-panel"><h2>JSON import</h2><p>Import systems, topics, runs, pipeline relationships, AI judges, and judgments in one atomic batch. Maximum 500 records / 2 MB. Duplicate IDs reject the entire batch.</p><label className="file-picker"><UploadSimpleIcon />Load JSON file<input type="file" accept=".json,application/json" onChange={async e => {const file=e.target.files?.[0]; if(file) {if(file.size>2_000_000) setError('File exceeds 2 MB'); else setJson(await file.text());}}} /></label><label>Import payload<textarea className="json-editor" spellCheck={false} value={json} onChange={e => setJson(e.target.value)} rows={20} /></label><button className="button dark" disabled={busy} onClick={() => void perform(() => api('/admin/import',{method:'POST',body:JSON.stringify(JSON.parse(json))},secret),'Bulk import completed atomically.')}><UploadSimpleIcon />Validate & import</button></section>}
    {tab === 'display' && <section><Select label="Response to edit" value={editId} onChange={v => void loadDisplay(v)} options={[["","Choose a response"],...references('responses')]} />{editId && <><div className="notice">Only display text changes. Raw output and historical Arena snapshots are preserved.</div><label>Blind Arena display<textarea rows={18} value={display} onChange={e => setDisplay(e.target.value)} /></label><button className="button dark" disabled={busy || !display} onClick={() => void perform(() => api(`/admin/responses/${editId}`,{method:'PATCH',body:JSON.stringify({display_output:display})},secret),'Display revision saved. Previous judgments retain their original snapshots.')}>Save display revision</button><details className="raw-output"><summary>Original raw output (read only)</summary><pre>{raw}</pre></details></>}</section>}
    {tab === 'catalog' && <section><h2>Systems and topics</h2><p className="muted">Inactive records remain in historical rankings, but are excluded from new Arena matchups.</p>{(['systems','topics'] as const).map(kind => <div className="catalog-section" key={kind}><h3>{kind === 'systems' ? 'Systems / configurations' : 'Topics'}</h3>{catalog[kind].map(record => <div className="catalog-row" key={record.id}><span><strong>{'display_name' in record ? record.display_name : record.motion}</strong><code>{record.id}</code></span><button className="button small" disabled={busy} onClick={() => void perform(() => api(`/admin/${kind}/${record.id}`,{method:'PUT',body:JSON.stringify({...record,active:record.active ? 0 : 1})},secret),'Active status updated.')}>{record.active ? 'Deactivate' : 'Activate'}</button></div>)}</div>)}</section>}
    {tab === 'weights' && <form className="weights-form" onSubmit={saveWeights}><h2>Source influence</h2><p className="muted">Fixed shares prevent a large AI vote import from overwhelming human judgment. Each group must total 100%.</p><div className="filter-row"><label>Human judges (%)<input name="human" type="number" min="0" max="100" step="0.1" defaultValue={catalog.source.human*100} required /></label><label>AI judges (%)<input name="ai" type="number" min="0" max="100" step="0.1" defaultValue={catalog.source.ai*100} required /></label></div>{Object.entries(TASK_LABELS).map(([task,label]) => <fieldset key={task}><legend>{label} metric weights (%)</legend><div className="weights-grid">{applicableMetrics(task).map(m => <label key={m}>{METRIC_LABELS[m]}<input type="number" name={`${task}:${m}`} min="0" max="100" step="0.1" defaultValue={(catalog.weights.find(w => w.task === task && w.metric === m)?.weight || 0)*100} required /></label>)}</div></fieldset>)}<button className="button dark" disabled={busy}>Save benchmark weights</button></form>}</>}</div>;
}
