import { applicableMetrics, type Metric } from '../shared/domain';

// Deliberately handcrafted fictional fixtures. No models or AI services are called.
const motions = [
  { id:'public-transit',motion:'This House would make public transport free at the point of use.',category:'Serious', subject:'public transport', problem:'the cost of daily travel', mechanism:'fare removal lowers the marginal cost of each journey', impact:'people with low incomes can reach work, education, and care more reliably' },
  { id:'citizens-assembly',motion:'This House would give citizens’ assemblies binding powers over climate policy.',category:'Serious', subject:'citizens’ assemblies', problem:'short electoral time horizons', mechanism:'a representative group can deliberate over long-term trade-offs', impact:'climate policy becomes less vulnerable to short-term electoral pressure' },
  { id:'four-day-week',motion:'This House would adopt a four-day working week without a reduction in pay.',category:'Serious', subject:'a shorter working week', problem:'persistent overwork', mechanism:'protected time off changes incentives to organize work efficiently', impact:'workers gain time for care and participation in their communities' },
  { id:'spoilers',motion:'This House believes that knowing the ending makes a story better.',category:'Informal', subject:'knowing a story’s ending', problem:'anxiety about what happens next', mechanism:'foreknowledge shifts attention from suspense to craft', impact:'audiences can appreciate foreshadowing, character choices, and structure' },
] as const;
const configurations = [
  ['demo-atlas','Atlas / Standard [DEMO]','Fictional Labs','Atlas-Example','Example Chat','Standard','No tools; fictional fixture.'],
  ['demo-atlas-tools','Atlas / Research [DEMO]','Fictional Labs','Atlas-Example','Example Research Workspace','Extended','Offline research configuration; fictional fixture.'],
  ['demo-cedar','Cedar / Deliberate [DEMO]','Illustrative Systems','Cedar-Example','Example Chat','Deliberate','No tools; fictional fixture.'],
  ['demo-orbit','Orbit / Workspace [DEMO]','Placeholder Research','Orbit-Example','Example Code Workspace','Not specified','Workspace and search were available offline; fictional fixture.'],
] as const;
const timestamp = '2026-09-01T12:00:00.000Z';
export function createDemoData() {
  const systems = configurations.map(([id,display_name,provider,model,iface,reasoning,configuration]) => ({id,display_name,provider,model,interface:iface,reasoning,configuration,active:1}));
  const topics = motions.map(({id,motion,category}) => ({id,motion,category,active:1,metadata_json:'{"demo":true}'}));
  const responses: Record<string,unknown>[] = [], predictions:{response_id:string}[] = [], rebuttals:{response_id:string;prediction_response_id:string;fresh_context:1}[] = [], preps:{response_id:string;prediction_response_id:string;rebuttal_response_id:string}[] = [];
  const standards = motions.map(t => ({id:`standard-${t.id}`,topic_id:t.id,title:`Shared case: ${t.subject}`,government_response_id:null,case_text:`## The shared Government case\n\nOur problem is ${t.problem}. We propose ${t.subject} because ${t.mechanism}.\n\nThe principal impact is that ${t.impact}. The policy should be evaluated against the status quo, including the costs of implementation and the consequences for those with the least choice.\n\nThis is a fictional demonstration case, with no empirical claims.`}));
  const outputs = new Map<string,string>();
  for (const [ti,t] of motions.entries()) for (const [si,s] of systems.entries()) {
    const lens = ['access and fairness','institutional incentives','practical feasibility','comparative opportunity costs'][si];
    const government = `## A case built around ${lens}\n\n**The central claim.** The problem with the status quo is ${t.problem}. Our case for ${t.subject} starts with who bears that cost and what they can realistically do about it.\n\n## 1. Establish the causal mechanism\n\nThe change matters because ${t.mechanism}. This is not a claim that everyone changes their behavior at once. The relevant question is whether the people at the margin gain an option they currently lack.\n\nConsider a hypothetical person whose choices are constrained by the current arrangement. A small change in those constraints can have a large effect on their ability to participate. The illustration clarifies the mechanism; it is not empirical evidence.\n\n## 2. Explain why the impact matters\n\nThe strongest benefit is that ${t.impact}. Prioritize people with the fewest alternatives: an equivalent improvement has greater practical value when the baseline is poor.\n\n- Identify the group affected most directly.\n- Trace the behavioral change rather than assuming it.\n- Compare the size, likelihood, and durability of the benefit.\n\n## 3. Win the comparative\n\nOpposition will argue that implementation costs or unintended consequences outweigh the benefit. Concede that these are real burdens. Then ask whether a narrower safeguard can manage them without preserving the original harm.\n\n**Strategic priority:** defend the causal link before broadening the case. A clear mechanism and a credible comparison are more valuable than an extra speculative impact.\n\n${si === 1 ? '## A useful distinction\n\nSeparate transitional disruption from the steady-state effect. A temporary cost cannot automatically defeat a durable benefit, but the burden of showing a workable transition remains with Government.' : si === 2 ? '## The limiting principle\n\nThe case weakens if the policy removes a constraint that was not actually binding. State what would have to be true for the mechanism to fail, and address that possibility directly.' : si === 3 ? '## The alternative\n\nCompare this proposal with a targeted intervention serving the most affected people. Government must explain why broader coverage is worth the additional cost.' : '## Closing comparison\n\nThis is a choice between two imperfect arrangements. The question is which leaves the least advantaged with a more realistic path to improvement.'}`;
    const prediction = `## The strongest Government case to expect\n\n**Primary argument: remove a binding constraint.** Government will say ${t.problem} prevents people from making choices that improve their lives. Expect them to claim that ${t.mechanism}.\n\n**Impact framing.** Their most persuasive conclusion is that ${t.impact}. They should focus on people with few alternatives, rather than claiming a uniform benefit.\n\n## Threat prioritization\n\n1. The causal mechanism is the central threat. If it stands, merely listing costs is insufficient.\n2. The distributional claim makes a modest aggregate benefit more morally salient.\n3. An implementation safeguard could neutralize a generic objection about feasibility.\n\n## Where to prepare a response\n\nTest whether the proposed change reaches the people described. Ask what else constrains behavior after the policy changes. Our analysis of ${lens} should identify a concrete counterfactual rather than deny all possible benefit.\n\nThis forecast is intentionally charitable: prepare against the strongest coherent version of the case.`;
    const rebuttal = `## Rebuttal to the predicted case\n\n**The missing link.** Even if ${t.mechanism}, the proposal does not automatically establish the size of the eventual benefit. There may be other constraints between the intervention and the impact.\n\n## Answer the priority claim\n\nThe strongest people-first argument is that ${t.impact}. Accept the importance of that goal. Challenge the comparison: could a more targeted change address ${t.problem} at lower cost or with fewer unintended consequences?\n\n## Comparative response\n\nUse ${lens} to distinguish a desirable outcome from a justified policy. A hypothetical case of success does not show the policy works for most affected people. Equally, a hypothetical failure does not prove that it never works.\n\n**Weighing:** identify the probability of the claimed gain, the people who bear the cost, and whether the consequences can be reversed.\n\n**What to concede:** the existing arrangement is imperfect. Opposition should defend a better alternative, not pretend the status quo has no harms.`;
    const constructive = `## Opposition constructive\n\nOur affirmative alternative addresses ${t.problem} through a narrower intervention. Center ${lens}, and explain what the alternative does for people who would otherwise be excluded.\n\n**Round priority:** first contest the mechanism, then establish the alternative. The case turns on which approach most reliably improves the position of those with the fewest choices.`;
    const standard = `## Answer to the common Government case\n\nThe case establishes a desirable objective, but leaves a comparative burden unresolved. It claims ${t.impact}; our response asks how reliably that follows from the intervention.\n\n## Direct clash\n\nThe proposed mechanism is that ${t.mechanism}. Identify the other constraints that remain. If they continue to block the outcome, a change to this one condition may have limited effect.\n\n## A better comparison\n\nFrom the perspective of ${lens}, a targeted alternative may reach the intended beneficiaries more consistently. Specify the trade-off rather than simply assert that the alternative is cheaper.\n\n## Weighing\n\nConcede plausible benefits. Then compare their probability and distribution with the opportunity cost. Government must show its proposal is preferable to the best available alternative, not merely preferable to doing nothing.`;
    for (const [task,output] of [['government',government],['prediction',prediction],['rebuttal',rebuttal],['full_opposition',constructive],['standardized_rebuttal',standard]]) {
      const id = `${s.id}-${t.id}-${task}`;
      responses.push({id,system_id:s.id,topic_id:t.id,task,standardized_task_id:task === 'standardized_rebuttal' ? `standard-${t.id}` : null,raw_output:`[FICTIONAL FIXTURE: ${s.display_name}]\n${output}\n\nSources: none. Handcrafted demonstration material.`,display_output:output,prompt:`[DEMO] Prepare ${task} for: ${t.motion}`,generated_at:timestamp,interface:s.interface,reasoning:s.reasoning,configuration:s.configuration,duration_ms:12000+si*2300+ti*300,sample:1,context_id:`ctx-${si}-${ti}-${task}`});
      outputs.set(id, output);
      if (task === 'prediction') predictions.push({response_id:id});
      if (task === 'rebuttal') rebuttals.push({response_id:id,prediction_response_id:`${s.id}-${t.id}-prediction`,fresh_context:1});
      if (task === 'full_opposition') preps.push({response_id:id,prediction_response_id:`${s.id}-${t.id}-prediction`,rebuttal_response_id:`${s.id}-${t.id}-rebuttal`});
    }
  }
  const ai_judges = [{id:'demo-judge-one',system_id:systems[0].id,display_name:'Example adjudicator I [DEMO]',version:'fixture-v1'},{id:'demo-judge-two',system_id:systems[2].id,display_name:'Example adjudicator II [DEMO]',version:'fixture-v1'}];
  const ai_votes: Record<string,unknown>[] = [];
  for (const [ti,t] of motions.entries()) for (const task of ['government','prediction','standardized_rebuttal','full_opposition']) for (let i=0;i<4;i++) for(let j=i+1;j<4;j++) for (const [ji,judge] of ai_judges.entries()) {
    const a = `${systems[i].id}-${t.id}-${task}`, b = `${systems[j].id}-${t.id}-${task}`;
    const overall = ((i*3+j+ti+ji)%5)-2;
    const metrics = Object.fromEntries(applicableMetrics(task).map((m,mi) => [m,((i+j+ti+ji+mi)%5)-2]));
    const snapshot = (id:string) => task === 'full_opposition' ? `## Government argument predictions\n\n${outputs.get(id.replace('full_opposition','prediction'))}\n\n## Rebuttals · fresh context\n\n${outputs.get(id.replace('full_opposition','rebuttal'))}\n\n## Constructive material\n\n${outputs.get(id)}` : outputs.get(id)!;
    ai_votes.push({id:`av-${ti}-${task}-${i}-${j}-${ji}`,judge_id:judge.id,response_a:a,response_b:b,overall,metrics,version:'fixture-v1',judged_at:timestamp,explanation:'Fabricated demonstration vote. Not a real AI evaluation.',snapshot_a:snapshot(a),snapshot_b:snapshot(b)});
  }
  return {systems,topics,standardized_rebuttal_tasks:standards,responses,opposition_predictions:predictions,opposition_rebuttals:rebuttals,opposition_preps:preps,ai_judges,ai_votes};
}
export const demoMetricVote = (metrics: Metric[], n:number) => Object.fromEntries(metrics.filter((_,i) => (n+i)%6 !== 0).map((m,i) => [m,((n+i)%5)-2]));
